### PR TITLE
Added support for API errors

### PR DESCRIPTION
**Pull request by dfcook**
Added deviceType of API to support sending errors from the backend to be logged in the eventsDb

### CODE REVIEW

**Comment by andrewmarklloyd** [comment]
This is great I was thinking that we needed this recently. In the future should we should put this in a different database than eventsDb though? https://github.com/SoftwareEngineeringDaily/sedaily-event-stream/blob/master/server/helpers/InfluxInterface.js#L4

**Comment by jasonify** [comment]
@andrewmarklloyd  @dfcook  how do you guys want to coordinate this deployment?

I am hoping to have this in so we can then deploy this backend PR (https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/pull/158#issuecomment-365704079)  even though technically it shouldn't break if the event-stream server is down. 


@andrewmarklloyd  once this PR is merged in, would you be able to handle the deployment of the event-stream?

**Comment by andrewmarklloyd** [comment]
@jasonify im out of town now but I could do it sometime in the next couple days. Would it have to be immediately after the merge?

**Comment by jasonify** [comment]
@andrewmarklloyd  No rush. Take your time. Just let me know when you are able to get this PR online.

**Comment by dfcook** [comment]
I've updated the PR to move errors to a new db, @jasonify I'll update the PR for the backend once this has been approved.

**Comment by andrewmarklloyd** [comment]
Awesome job @dfcook! @jasonify this is deployed now

**Pull request merged**
